//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_MVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNhapSach
    {
        public int ID { get; set; }
        public int IDNpp { get; set; }
        public int IDSach { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public System.DateTime NgayNhap { get; set; }
    
        public virtual NhaPhanPhoi NhaPhanPhoi { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
