//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_MVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTraSach
    {
        public int IDPt { get; set; }
        public int IDSach { get; set; }
        public int SoLuong { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhieuTra PhieuTra { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
